import { useState } from 'react';
import { api } from '../api';

const PLACE_SUGGESTIONS = ['Whitefield', 'Koramangala', 'HSR Layout', 'Indiranagar', 'Bellandur', 'Marathahalli', 'Electronic City', 'Jayanagar', 'JP Nagar', 'Hebbal', 'Yelahanka', 'MG Road', 'BTM Layout', 'Sarjapur', 'Mahadevapura', 'Hoodi', 'KR Puram', 'Kalyan Nagar', 'Hennur', 'RT Nagar', 'Sahakar Nagar', 'Malleshwaram', 'Rajajinagar', 'Vijayanagar', 'Basavanagudi', 'Banashankari', 'Bannerghatta Road', 'Kanakapura Road', 'Begur', 'Kudlu Gate', 'Singasandra', 'Domlur', 'Ulsoor', 'Frazer Town', 'Yemalur', 'RR Nagar', 'Kengeri', 'Embassy Tech Village', 'RMZ Ecospace', 'Manyata Tech Park', 'Bagmane Tech Park', 'ITPL', 'Prestige Tech Park'];

export default function LocationSearch({ token, onResults }) {
  const [query, setQuery] = useState(''); const [radiusKm, setRadiusKm] = useState(5); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [open, setOpen] = useState(false);
  const suggestions = query.trim().length < 2 ? [] : PLACE_SUGGESTIONS.filter(place => place.toLowerCase().includes(query.toLowerCase())).slice(0, 6);
  const search = async event => { event.preventDefault(); setLoading(true); setError(''); try { const { location } = await api(`/listings/geocode?query=${encodeURIComponent(query)}`, { token }); const { listings, nearest } = await api(`/listings?lat=${location.latitude}&lng=${location.longitude}&radiusKm=${radiusKm}`, { token }); onResults({ listings, origin: location, nearest }); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  return <form className="location-search" onSubmit={search}><h2>Search near a place</h2><p className="muted">Enter an office, landmark, or neighbourhood. This search location is not saved.</p><div className="suggestion-input"><input required minLength="3" value={query} onFocus={() => setOpen(true)} onBlur={() => window.setTimeout(() => setOpen(false), 150)} onChange={e => { setQuery(e.target.value); setOpen(true); }} placeholder="e.g. Embassy Tech Village" />{open && suggestions.length > 0 && <ul className="suggestions" role="listbox">{suggestions.map(place => <li key={place}><button type="button" onMouseDown={() => { setQuery(place); setOpen(false); }}>{place}</button></li>)}</ul>}</div><label>Within {radiusKm} km<input type="range" min="1" max="50" value={radiusKm} onChange={e => setRadiusKm(e.target.value)} /></label>{error && <p className="error">{error}</p>}<button disabled={loading}>{loading ? 'Searching…' : 'Search properties'}</button></form>;
}
