import { useEffect, useState } from 'react';
import { api, notifyError } from './api';
import ListingCard from './components/ListingCard';
import HostReviewDashboard from './components/HostReviewDashboard';
import ListingMap from './components/ListingMap';
import LocationSearch from './components/LocationSearch';
import MyListings from './components/MyListings';
import { supabase } from './supabase';

const initialForm = { name: '', email: '', phone: '', password: '', role: 'Seeker', professionTitle: '', workRoutine: 'Hybrid', hobbies: '' };
const BENGALURU_AREAS = ['HSR Layout', 'Indiranagar', 'Whitefield', 'Koramangala', 'Bellandur', 'Marathahalli', 'Electronic City', 'Jayanagar', 'JP Nagar', 'Hebbal', 'Yelahanka', 'MG Road', 'BTM Layout', 'Sarjapur', 'Mahadevapura', 'Hoodi', 'KR Puram', 'Kalyan Nagar', 'Hennur', 'RT Nagar', 'Sahakar Nagar', 'Malleshwaram', 'Rajajinagar', 'Vijayanagar', 'Basavanagudi', 'Banashankari', 'Bannerghatta Road', 'Kanakapura Road', 'Begur', 'Kudlu Gate', 'Singasandra', 'Domlur', 'Ulsoor', 'Frazer Town', 'Yemalur', 'RR Nagar', 'Kengeri'];
function Auth({ onAuthenticated }) {
  const [registering, setRegistering] = useState(true); const [form, setForm] = useState(initialForm); const [error, setError] = useState('');
  const submit = async event => { event.preventDefault(); setError(''); try {
    const profile = { ...form, hobbyMatrix: form.hobbies.split(',').map(x => x.trim()).filter(Boolean) };
    if (!supabase) { const body = registering ? profile : { email: form.email, password: form.password }; return onAuthenticated(await api(`/auth/${registering ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(body) })); }
    const result = registering ? await supabase.auth.signUp({ email: form.email, password: form.password }) : await supabase.auth.signInWithPassword({ email: form.email, password: form.password });
    if (result.error) throw result.error;
    if (!result.data.session) { setError('Check your email to confirm your account, then sign in.'); return; }
    const { user } = await api('/auth/bootstrap', { token: result.data.session.access_token, method: 'POST', body: JSON.stringify(profile) });
    onAuthenticated({ token: result.data.session.access_token, user, provider: 'supabase' });
  } catch (e) { if (!e.notified) notifyError(e.message); setError(e.message); } };
  const providerName = supabase ? 'Supabase' : 'local development';
  return <main className="auth"><h1>Bengaluru VibeMatch</h1><p>Find a home that fits your rhythm. Secure login: {providerName}.</p><form onSubmit={submit}><h2>{registering ? 'Create your profile' : 'Welcome back'}</h2>{registering && <><input required placeholder="Name" value={form.name} onChange={e => setForm({...form, name:e.target.value})}/><input required placeholder="Phone" value={form.phone} onChange={e => setForm({...form, phone:e.target.value})}/><select value={form.role} onChange={e => setForm({...form, role:e.target.value})}><option>Seeker</option><option>Host</option><option>Both</option></select><input placeholder="Profession" value={form.professionTitle} onChange={e => setForm({...form, professionTitle:e.target.value})}/><select value={form.workRoutine} onChange={e => setForm({...form, workRoutine:e.target.value})}><option>Fully Remote</option><option>Hybrid</option><option>Office Commute</option></select><input placeholder="Hobbies (comma-separated)" value={form.hobbies} onChange={e => setForm({...form, hobbies:e.target.value})}/></>}<input required type="email" placeholder="Email" value={form.email} onChange={e => setForm({...form, email:e.target.value})}/><input required minLength="10" type="password" placeholder="Password (10+ characters)" value={form.password} onChange={e => setForm({...form, password:e.target.value})}/>{error && <p className="error">{error}</p>}<button>{registering ? 'Join VibeMatch' : 'Sign in'}</button></form><button className="link-button" onClick={() => setRegistering(!registering)}>{registering ? 'Already have an account? Sign in' : 'Need an account? Register'}</button></main>;
}
function ListingForm({ token, onCreated }) {
  const [form, setForm] = useState({ location: '', duration: 'Long-term (11+ months)', description: '', availableFrom: '', rent: '', deposit: '', maintenance: '', maidFee: '', wifiSplit: '', petFriendly: false, gatedSociety: false }); const [files, setFiles] = useState([]); const [error, setError] = useState('');
  const update = e => setForm({ ...form, [e.target.name]: e.target.type === 'checkbox' ? e.target.checked : e.target.value });
  const submit = async e => { e.preventDefault(); try { const { location, duration, description, availableFrom, rent, deposit, maintenance, maidFee, wifiSplit, petFriendly, gatedSociety } = form; let { listing } = await api('/listings', { token, method: 'POST', body: JSON.stringify({ location, duration, description, availableFrom, costs: { rent: Number(rent), deposit: Number(deposit), maintenance: Number(maintenance), maidFee: Number(maidFee), wifiSplit: Number(wifiSplit) }, propertyRules: { petFriendly, gatedSociety } }) }); if (files.length) { const upload = new FormData(); files.forEach(file => upload.append('media', file)); const { media } = await api(`/listings/${listing._id}/media`, { token, method: 'POST', body: upload }); listing = { ...listing, media }; } onCreated(listing); } catch (e) { setError(e.message); } };
  return <form className="listing-form" onSubmit={submit}><h3>Post a listing</h3><label>Approximate neighbourhood (shown on map, never your address)<select required name="location" value={form.location} onChange={update}><option value="" disabled>Select an area</option>{BENGALURU_AREAS.map(area => <option key={area}>{area}</option>)}</select></label><label>Available from<input required type="date" name="availableFrom" value={form.availableFrom} onChange={update}/></label><textarea required name="description" maxLength="2000" value={form.description} onChange={update} placeholder="Describe the room, flat, commute, and flatmate vibe"/><label>Photos and videos (up to 8; JPG, PNG, WebP, MP4, or WebM; 30 MB each)<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple onChange={e => setFiles([...e.target.files].slice(0, 8))}/></label><select name="duration" value={form.duration} onChange={update}><option>Long-term (11+ months)</option><option>Short-term (1-6 months)</option><option>Flexible</option></select>{['rent','deposit','maintenance','maidFee','wifiSplit'].map(name => <input key={name} required={name === 'rent'} type="number" min="0" name={name} placeholder={name} value={form[name]} onChange={update}/>)}<label><input name="petFriendly" type="checkbox" onChange={update}/> Pet friendly</label><label><input name="gatedSociety" type="checkbox" onChange={update}/> Gated society</label>{error && <p className="error">{error}</p>}<button>Publish listing</button></form>;
}
export default function App() {
  const [session, setSession] = useState(null); const [authReady, setAuthReady] = useState(false); const [listings, setListings] = useState([]); const [origin, setOrigin] = useState(null); const [nearest, setNearest] = useState(null); const [error, setError] = useState('');
  // Cookie sessions are primary. Keep the issued bearer token as a compatibility
  // fallback for Vite/dev proxy setups that do not retain a proxied Set-Cookie header.
  const loggedIn = data => { const stored = data.provider === 'supabase' ? data : { token: data.token, user: data.user, provider: 'local' }; localStorage.setItem('vibematch-session', JSON.stringify(stored)); setSession(stored); };
  useEffect(() => { let active = true; (async () => { try { const cached = JSON.parse(localStorage.getItem('vibematch-session') || 'null'); if (supabase) { const { data } = await supabase.auth.getSession(); if (data.session) { const { user } = await api('/auth/bootstrap', { token: data.session.access_token, method: 'POST', body: JSON.stringify({}), silent: true }); if (active) loggedIn({ token: data.session.access_token, user, provider: 'supabase' }); } } else { const { user } = await api('/auth/session', { token: cached?.token, silent: true }); if (active) loggedIn({ user, provider: 'local' }); } } catch (_) { localStorage.removeItem('vibematch-session'); } finally { if (active) setAuthReady(true); } })(); return () => { active = false; }; }, []);
  useEffect(() => { if (session) api('/listings', { token: session.token }).then(({listings}) => setListings(listings)).catch(e => setError(e.message)); }, [session]);
  if (!authReady) return <main className="auth"><p>Restoring your session…</p></main>;
  if (!session) return <Auth onAuthenticated={loggedIn} />;
  const host = ['Host','Both'].includes(session.user.role);
  const signOut = () => { api('/auth/logout', { method: 'POST', silent: true }).catch(() => {}); if (session.provider === 'supabase') supabase?.auth.signOut(); localStorage.removeItem('vibematch-session'); setSession(null); };
  return <main><header><h1>Bengaluru VibeMatch</h1><button onClick={signOut}>Sign out</button></header>{error && <p className="error">{error}</p>}{host && <><ListingForm token={session.token} onCreated={listing => setListings(old => [{ ...listing, host: session.user }, ...old])}/><MyListings token={session.token} onUpdated={updated => setListings(old => old.map(x => x._id === updated._id ? { ...x, ...updated } : x))} onDeleted={id => setListings(old => old.filter(x => x._id !== id))}/></>}<LocationSearch token={session.token} onResults={({ listings, origin, nearest }) => { setListings(listings); setOrigin(origin); setNearest(nearest); }}/>{nearest && <section className="travel-estimate"><strong>Closest match: {nearest.label}</strong><span>Estimated road travel: {nearest.estimatedRoadKm} km · Direct distance: {nearest.distanceKm} km</span><small>Road distance is an estimate, not turn-by-turn navigation.</small></section>}<ListingMap listings={listings} origin={origin} nearest={nearest}/><section><h2>Homes available now</h2><p className="muted">{listings.length} {listings.length === 1 ? 'property' : 'properties'} available</p>{listings.length === 0 ? <p className="muted">No available properties match this search.</p> : <div className="grid">{listings.map(listing => <ListingCard key={listing._id} listing={listing} token={session.token} onRequestCreated={request => setListings(old => old.map(x => x._id === listing._id ? { ...x, myRequest: request } : x))}/>)}</div>}</section>{host && <HostReviewDashboard token={session.token}/>}</main>;
}
